name: Trigger auto deployment for con-app-amy0901

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/con-app-amy0901-AutoDeployTrigger-1ecebfa9-5ce6-4aee-bcbd-b9d6a4a6d0aa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONAPPAMY0901_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONAPPAMY0901_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONAPPAMY0901_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: amyregistry0901.azurecr.io
          registryUsername: ${{ secrets.CONAPPAMY0901_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONAPPAMY0901_REGISTRY_PASSWORD }}
          containerAppName: con-app-amy0901
          resourceGroup: conapp-env-0901
          imageToBuild: amyregistry0901.azurecr.io/con-app-amy0901:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


